# Generated by Django 5.2.1 on 2025-05-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['id'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='media_avaliacoes',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
